title: HZ Labs
description: "Codes, bugs and obligatory rants"
# disqus_shortname: 
#Comment out url when working locally to resolve base urls correctly
# url:              http://your-website.com

# Analytics and webmaster tools stuff goes here
# google_analytics: UA-XXXXX-X

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title/

# Amount of post to show on home page
paginate: 20

include: [".htaccess"]
exclude: ["less", "coffee", "*.sublime-project", "*.sublime-workspace", "package.json", "node_modules"]

pygments:    true
markdown:    kramdown

siteurl: 'http://hzdg.github.io/'

# Owner information
owner:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   

contributors:
  aebsr:
    name: Antoine Bulter
    gravatar: a0ec088786da70f0f0a7d29774533ef8
    twitter: aebsr
    github: aebsr
  kkubasik:
    name: Kevin Kubasik
    gravatar: 952aa92c2f88da8b18e45cff8e6897fc
    twitter: kkubasik
    github: kkubasik
  matthewwithanm:
    name: Matthew Tretter
    gravatar: 0e631d686b8356102da3721bd8cd65c4
    twitter: matthewwithanm
    github: matthewwithanm

static_pages:
  - name: 'Meet HZ'
    url: 'http://hzdg.com'
  # - name: 'Labs Archive'
  #   url: '/archive/'

prose:
  rooturl: '_posts'
  siteurl: 'http://hzdg.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "Text used as blog intro on listing pages as well as description metadata"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "HTML5"
              value: "html5"
            - name: "CSS3"
              value: "css3"
            - name: "Python"
              value: "python"
            - name: "Django"
              value: "django"
            - name: "Javascript"
              value: "javascript"
            - name: "LESS"
              value: "less"
            - name: "Coffeescript"
              value: "coffeescript"
            - name: "DC Tech"
              value: "#dctech"
            - name: "Community"
              value: "Community"
            - name: "Jekyll"
              value: "jekyll"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          options:
            - name: "Kevin Kubasik"
              value: "kkubasik"
            - name: "Antoine Butler"
              value: "kkubasik"
            - name: "Matthew Tretter"
              value: "matthewwithanm"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
